name: "RedSock/TagReleaser"
description: "Creates tag based on version of matreshka config file "

author: "RedSock"

branding:
  icon: "git-pull-request"
  color: "red"

inputs:
  config_path:
    description: "Path to matreshka config file"
    default: "./config/config.yaml"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}

    - name: Obtain current tag
      id: current_tag
      shell: bash
      run: |
        echo "tag=$(echo $(git describe --tags))" >> $GITHUB_OUTPUT

    - name: Setup Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.8

    - name: Obtain tag
      id: config_tag
      env:
        INPUT_CONFIG_PATH: ${{ inputs.config_path }}
      shell: python
      run: |
        import yaml
        import os
        import subprocess
        ### Obtaining github latest tag
        current_tag = str(subprocess.run(['git', 'describe', '--tags'], stdout=subprocess.PIPE).stdout)
      
        with open(os.environ['INPUT_CONFIG_PATH']) as config_file:
          config_tag = yaml.safe_load(config_file)
          config_tag = config_tag['app_info']['version']
        
        if config_tag > current_tag:
          subprocess.run(['gh', 'release', 'create', config_tag, '--latest', '--target', '"${GITHUB_HEAD_REF}"'])