name: master-actions
run-name: RELEASE
on:
  push:
    branches:
      - master

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        id: release
        uses: RedSockActions/release_tag@76981aacedd342f76bd47d32d013023f849c4b9a
        with:
          token: ${{ github.token }}
      - name: Read new tag
        run: echo ${{ steps.release.outputs.tag }}