name: master-actions
run-name: RELEASE
on:
  push:
    branches:
      - master

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        id: release
        uses: RedSockActions/release_tag@0212e12bdf00d3287a8514ce14420e92e9807d83
        with:
          token: ${{ github.token }}
      - name: Read new tag
        run: echo ${{ steps.release.outputs.tag }}