name: master-actions
run-name: RELEASE
on:
  push:
    branches:
      - master

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        id: release
        uses: RedSockActions/release_tag@b3edda99511261ff42fdf38184561861fb392c9b
        with:
          token: ${{ github.token }}
      - name: Read new tag
        run: echo ${{ steps.release.outputs.new_tag }}